### ISSUE TITLE
[BUG] Unable to login to an existing profile

### ISSUE THREAD

**Issue by richtera** [lukso-network/docs#321]
**Describe the bug**
After moving to a new computer and installing the universal profile extension there is no way to import an existing profile. This makes the extension not very useful for testing. I understand that it's not production code, but without this you're like to a particular device or browser. I now have 4 universal profiles which no longer makes them very universal.

**Screenshots**
![image](https://user-images.githubusercontent.com/708186/181995961-8cf03e19-960e-4a7a-9c5d-118969d96889.png)

**Link**
Browser home clicking on extension the first time.

This doesn't seem the right repo to put this defect, however the installation page only has this link.

**Comment by Hugoo** [comment]
Hey thanks richtera for your PR.

We are aware of this missing issue and we are currently working on an import feature.

Also, we have a dedicated issue tracker for this project, you can find it here:

https://github.com/lukso-network/issue-tracker/issues

If you could open this issue on the two above it would be amazing.

Thanks 😊

**Comment by Hugoo** [comment]
Issue has been moved here:

https://github.com/lukso-network/issue-tracker/issues/9

Closing.
