### ISSUE TITLE
LSP8 transferBatch

### ISSUE THREAD

**Issue by jxyang44** [lukso-network/docs#328]
**Describe the bug**
2 minor typos, boxed in red.  Wording seems to be carried over from the LSP7 page.

**Screenshots**
![image](https://user-images.githubusercontent.com/58372066/182261791-6f4f10b2-1677-4e14-a331-7702132e3705.png)

**Link**
[Link](https://docs.lukso.tech/standards/smart-contracts/lsp8-identifiable-digital-asset)

**Comment by YamenMerhi** [comment]
Hello @jxyang44 
Thanks for reporting! Indeed these need to be changed. 
Do you want to do the PR or should I do it myself?

**Comment by jxyang44** [comment]
Hey Yamen I went ahead and made the pull request.
