### ISSUE TITLE
[BUG] "uploadMetaData" to "uploadProfileData"

### ISSUE THREAD

**Issue by jxyang44** [lukso-network/docs#341]
Was "uploadMetaData" changed to "uploadProfileData"? Docs still use "uploadMetaData"

https://docs.lukso.tech/tools/lsp-factoryjs/deployment/universal-profile

**Comment by Hugoo** [comment]
Hey - thanks for the issue - good point! We will take care of this issue in the upcoming sprints. Thanks

**Comment by kalote** [comment]
Fixed
