### ISSUE TITLE
[BUG] api.ipfs.lukso.network doesn't work anymore 

### ISSUE THREAD

**Issue by MatteoLeonesi** [lukso-network/docs#357]
**Describe the bug**
TypeErorr : failed to fetch here [ipfs](https://anarkrypto.github.io/upload-files-to-ipfs-from-browser-panel/public/#) while adding  api.ipfs.lukso.network  port:443

maybe the correct address is : api.2eff.lukso.dev 

**Screenshots**

![](https://cdn.discordapp.com/attachments/1005437292560777226/1007202714331123723/Screenshot_2022-08-11_at_10.23.52.png)

**Link**
[link to the page that you see this issue.
](https://anarkrypto.github.io/upload-files-to-ipfs-from-browser-panel/public/#)

**Comment by Hugoo** [comment]
Hey thanks for flagging ! This has been fixed in this PR:
https://github.com/lukso-network/docs/pull/431

;)
