### ISSUE TITLE
[BUG] Technical Lightpaper link dead

### ISSUE THREAD

**Issue by sandoche** [lukso-network/docs#451]
The link to the technical lightpaper is dead: https://lukso.network/assets/LUKSO_Technical_Lightpaper.pdf

In this file:
https://github.com/lukso-network/docs/blob/main/docs/faq/lukso.md

**Comment by Hugoo** [comment]
Hey hi @sandoche ! Thanks for flagging this!

We changed the links when we updated our website and it created this dead link. I'll ask internally so we can fix that. ;)
