### ISSUE TITLE
Update links for the faucet on docs and other areas

### ISSUE THREAD

**Issue by 34r7h** [lukso-network/docs#588]
https://faucet.testnet.lukso.network/

And make it clear it won't work on L16

**Comment by Hugoo** [comment]
Hey hi, the link is already here:

![image](https://github.com/lukso-network/docs/assets/477945/efb8cd5e-958c-463e-85c5-4006bac813c3)

https://docs.lukso.tech/networks/testnet/parameters

It is on TESTNET page (not L16) so it is good.

Is there anything else you want to flag? I will close for now. Please feel free to answer and re open if needed.

Thanks
