### ISSUE TITLE
[DOC] Typos & improvements

### ISSUE THREAD

**Issue by Heisenburgirs** [lukso-network/docs#722]
Here are some typos I've found over past few days building for Lukso's Build up #25 

1. Missing comma

![image](https://github.com/lukso-network/docs/assets/129852498/9fd52449-c5e3-4371-997e-cb363c4cec9b)

2. Full code at the end rather than before the last piece of code for testing the results

![image](https://github.com/lukso-network/docs/assets/129852498/604ae263-9395-4ef6-aed8-bac083388c2f)

**Comment by Hugoo** [comment]
Hey!

Thanks a lot for flagging! I sent the changes in this PR:

https://github.com/lukso-network/docs/pull/723
