### ISSUE TITLE
[DOC] Double Trouble

### ISSUE THREAD

**Issue by Heisenburgirs** [lukso-network/docs#845]
Refer to transfer() function explanation within - https://github.com/lukso-network/LIPs/blob/main/LSPs/LSP-7-DigitalAsset.md

You'll see duplicate text:

![image](https://github.com/lukso-network/LIPs/assets/129852498/c68d6a9d-cc2a-40db-ab92-d4e1a226fcea)

**Comment by Hugoo** [comment]
hey @Heisenburgirs - one is with `SenderNotification` and the other bullet point is with `RecipientNotification`

- or is it confusing?

**Comment by Heisenburgirs** [comment]
Ohh... you're right, didn't notice it, I was going through it quickly.

Maybe have distinction between them:

**When token recipient supports LSP1 interface:**
....

**When token sender supports LSP1 interface**
...

**Comment by Hugoo** [comment]
@CJ42

**Comment by Hugoo** [comment]
I will close this issue here. I opened a PR in the LIPs repo:

https://github.com/lukso-network/LIPs/pull/286
