### ISSUE TITLE
[BUG] The beginning of a sentence should start with a capital letter

### ISSUE THREAD

**Issue by jnorbert** [lukso-network/docs#92]
**Describe the bug**
The beginning of a sentence should start with a capital letter.

> allowing state changes at the address being called.

**Screenshots**
<img width="2555" alt="doc" src="https://user-images.githubusercontent.com/13810654/149119934-057bb8c6-c499-4fb7-9e61-35048984646a.png">

**Link**
https://docs.lukso.tech/standards/universal-profile/lsp6-key-manager

**Comment by Hugoo** [comment]
Solved here: https://github.com/lukso-network/docs/commit/f33e56268c851d77adc2b71107bfee83ef664cb2
